{
 "title": "vCenter View",
 "tags": [
  "vmware",
  "vcenter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "20s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(vmware_vcenter_info,job)"
    }
   },
   {
    "name": "vcenter",
    "label": "vCenter",
    "query": {
     "query": "label_values(vmware_vcenter_info{job=\"$job\"},vcenter)"
    }
   },
   { "name": "top", "label": "Top", "query": "5,10,20,30,40,50,100" }
  ]
 },
 "panels": [
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    vmware_host_info{vcenter=~\"$vcenter\"}\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    vmware_vm_info{vcenter=~\"$vcenter\"}\n    )",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  vmware_host_cpu_usagemhz_average{vcenter=~\"$vcenter\"}\n) /\nsum(\n  vmware_host_cpu_capacity{vcenter=~\"$vcenter\"} * \n  vmware_host_cpu_corecount{vcenter=~\"$vcenter\"}\n) \n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_host_mem_consumed_average{vcenter=~\"$vcenter\"} * 1024) / \nsum(vmware_host_mem_capacity{vcenter=~\"$vcenter\"})\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Provisioned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    vmware_datastore_capacity{vcenter=~\"$vcenter\"}\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(\n    vmware_datastore_capacity{vcenter=~\"$vcenter\"}\n  ) -\n  sum(\n    vmware_datastore_free{vcenter=~\"$vcenter\"}\n  )\n) /\nsum(\n  vmware_datastore_capacity{vcenter=~\"$vcenter\"}\n)\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    vmware_datastore_free{vcenter=~\"$vcenter\"}\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "vCenter Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(\n    vmware_vcenter_info{vcenter=~\"$vcenter\"},\n    \"newversion\", \".\",\"version\", \"patch\"\n)",
     "legendFormat": "{{vcenter}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_sys_uptime_latest{vcenter=~\"$vcenter\", vm=~\"$vcenter\"}  ",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    vmware_host_cpu_corecount{vcenter=~\"$vcenter\"}\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    vmware_host_mem_capacity{vcenter=~\"$vcenter\"}\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Hosts Inventory",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\n  label_join(\n    label_replace(\n      vmware_host_hardware_info{vcenter=~\"$vcenter\"},\n      \"vendor\", \"$1\", \"vendor\", \"(.*) .*\"\n    ),\n    \"newmodel\", \" \",\"vendor\", \"model\"\n  ), \"cpu_type\", \"$1 $3 $5\", \"cpu_type\", \"(.*)(\\\\(R\\\\))(.*)(\\\\(R\\\\))(.*) CPU @.*\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\n    label_replace(\n        vmware_host_software_info{vcenter=~\"$vcenter\"},\n        \"build\", \"($1)\", \"build\", \"(.*)\"\n    ),\n    \"os\",\" \",\"software\",\"version\",\"build\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware_host_cpu_corecount{vcenter=~\"$vcenter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware_host_cpu_capacity{vcenter=~\"$vcenter\"} * 1000 * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware_host_mem_capacity{vcenter=~\"$vcenter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware_host_sys_uptime_latest{vcenter=~\"$vcenter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware_host_cpu_threadcount{vcenter=~\"$vcenter\"} / \nvmware_host_cpu_corecount{vcenter=~\"$vcenter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Capacity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    vmware_host_cpu_capacity{vcenter=~\"$vcenter\"} *\n    vmware_host_cpu_corecount{vcenter=~\"$vcenter\"} * \n    1000 * 1000\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    vmware_host_mem_capacity{vcenter=~\"$vcenter\"}\n) - \nsum(\n    vmware_host_mem_consumed_average{vcenter=~\"$vcenter\"} * 1024\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    vmware_host_cpu_capacity{vcenter=~\"$vcenter\"} *\n    vmware_host_cpu_corecount{vcenter=~\"$vcenter\"} * \n    1000 * 1000\n) - \nsum(\n    vmware_host_cpu_usagemhz_average{vcenter=~\"$vcenter\"} * 1000 * 1000\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory GB per Core",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    vmware_vm_mem_capacity{vcenter=~\"$vcenter\"}\n) / \nsum(\n   vmware_host_cpu_corecount{ vcenter=~\"$vcenter\"}\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU Overcommit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  vmware_vm_cpu_corecount{vcenter=~\"$vcenter\"}\n)\n/ \nsum(\n  vmware_host_cpu_threadcount{vcenter=~\"$vcenter\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Overcommit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  vmware_vm_mem_capacity{vcenter=~\"$vcenter\"} *\n  1024 * 1024\n)\n/\nsum(\n  vmware_host_mem_capacity{vcenter=~\"$vcenter\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  vmware_host_cpu_usagemhz_average{vcenter=~\"$vcenter\"}\n) / \nsum(\n  vmware_host_cpu_capacity{vcenter=~\"$vcenter\"} *\n  vmware_host_cpu_corecount{vcenter=~\"$vcenter\"}\n) \n* 100",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(\n    vmware_host_cpu_latency_average{vcenter=~\"$vcenter\"}\n) / 100",
     "legendFormat": "Latency"
    },
    {
     "expr": "avg(\n    sum(\n        vmware_host_cpu_ready_summation{vcenter=~\"$vcenter\"} / (20 * 1000)\n    ) /\n    sum(\n        vmware_host_cpu_corecount{vcenter=~\"$vcenter\"}\n    ) \n)\n* 100",
     "legendFormat": "Ready"
    },
    {
     "expr": "avg(\n    vmware_host_cpu_costop_summation{vcenter=~\"$vcenter\"} / (20 * 1000)\n) \n* 100",
     "legendFormat": "Costop"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n    vmware_host_mem_consumed_average{vcenter=~\"$vcenter\"} * 1024\n) / \nsum(\n    vmware_host_mem_capacity{vcenter=~\"$vcenter\"}\n)\n* 100",
     "legendFormat": "Consumed"
    },
    {
     "expr": "sum(\n    vmware_host_mem_active_average{vcenter=~\"$vcenter\"} * 1024\n) / \nsum(\n    vmware_host_mem_capacity{vcenter=~\"$vcenter\"}\n)\n* 100",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(\n    vmware_host_mem_shared_average{vcenter=~\"$vcenter\"} * 1024\n)/ \nsum(\n    vmware_host_mem_capacity{vcenter=~\"$vcenter\"}\n)\n* 100",
     "legendFormat": "Shared"
    },
    {
     "expr": "sum(\n    vmware_host_mem_vmmemctl_average{vcenter=~\"$vcenter\"} * 1024\n)/ \nsum(\n    vmware_host_mem_capacity{vcenter=~\"$vcenter\"}\n)\n* 100",
     "legendFormat": "Ballooned"
    }
   ]
  },
  {
   "title": "Top $top Datastores per Storage Used",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk_avg($top,\n  (\n    vmware_datastore_capacity{vcenter=~\"$vcenter\"} - \n    vmware_datastore_free{vcenter=~\"$vcenter\"}\n  ) /\n  vmware_datastore_capacity{vcenter=~\"$vcenter\"} * 100\n)",
     "legendFormat": "{{ds}}"
    }
   ]
  }
 ]
}