{
 "title": "VM View",
 "tags": [
  "vmware",
  "vm"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "20s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "vcenter",
    "label": "vCenter",
    "query": {
     "query": "label_values(vmware_vcenter_info{},vcenter)"
    }
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(vmware_datacenter_info{vcenter=~\"$vcenter\"},dc)"
    }
   },
   {
    "name": "dcmo",
    "query": {
     "query": "label_values(vmware_datacenter_info{vcenter=~\"$vcenter\", dc=~\"$datacenter\"},dcmo)"
    }
   },
   {
    "name": "dchostfolder",
    "query": {
     "query": "label_values(vmware_folder_info{vcenter=~\"$vcenter\", dcmo=~\"$dcmo\", dc=\"host\"},foldermo)"
    }
   },
   {
    "name": "computemo",
    "query": {
     "query": "label_values(vmware_compute_info{vcenter=~\"$vcenter\", foldermo=~\"$dchostfolder\"}, cmo)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vmware_cluster_info{vcenter=~\"$vcenter\", foldermo=~\"$dchostfolder\"},vmwcluster)"
    }
   },
   {
    "name": "clustermo",
    "query": {
     "query": "label_values(vmware_cluster_info{vcenter=~\"$vcenter\", foldermo=~\"$dchostfolder\", vmwcluster=~\"$cluster\"}, cmo)"
    }
   },
   {
    "name": "hostmolist",
    "query": {
     "query": "label_values(vmware_host_info{vcenter=~\"$vcenter\", cmo=~\"$computemo|$clustermo\"}, hostmo)"
    }
   },
   {
    "name": "vm",
    "label": "VirtualMachine",
    "query": {
     "query": "label_values(vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmolist\"}, vm)"
    }
   },
   {
    "name": "vmmo",
    "query": {
     "query": "label_values(vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmolist\", vm=~\"$vm\"}, vmmo)"
    }
   },
   {
    "name": "hostmo",
    "query": {
     "query": "label_values(vmware_vm_info{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\", vm=~\"$vm\"}, hostmo)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "vCPUs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_corecount{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"}",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} / \n(\n  scalar(vmware_host_cpu_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}) *\n  scalar(vmware_vm_cpu_corecount{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"})\n) \n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(\n    vmware_vm_mem_active_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"}\n) / \n(\n    vmware_vm_mem_capacity{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} * 1024\n)\n* 100\n",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} * 1000 * 1000",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "CPU Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_demand_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} / \nvmware_vm_cpu_entitlement_latest{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"}",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "CPU Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_latency_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} / 100 ",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Data on Disk",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_datastore_capacity_used{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"}",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}  ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "vMemory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_capacity{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"}",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Active Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_active_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"}",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_sys_uptime_latest{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"}  ",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} / \n(\n  scalar(\n    vmware_host_cpu_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n  ) *\n  scalar(\n    vmware_vm_cpu_corecount{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"}\n  )\n) \n* 100",
     "legendFormat": "Usage"
    },
    {
     "expr": "vmware_vm_cpu_latency_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} / 100",
     "legendFormat": "Latency"
    },
    {
     "expr": "(\n    scalar(\n        vmware_vm_cpu_ready_summation{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} \n    ) / (20 * 1000)\n) /\nvmware_vm_cpu_corecount{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} * 100",
     "legendFormat": "Ready"
    },
    {
     "expr": "(\n    vmware_vm_cpu_costop_summation{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} \n    / (20 * 1000)\n) * 100",
     "legendFormat": "Costop"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "scalar(\nvmware_vm_mem_consumed_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"}\n) / \n(\n    vmware_vm_mem_capacity{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} * 1024\n)\n* 100",
     "legendFormat": "Consumed"
    },
    {
     "expr": "scalar(\n    vmware_vm_mem_active_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"}\n) / \n(\n    vmware_vm_mem_capacity{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} * 1024\n)\n* 100",
     "legendFormat": "Active"
    },
    {
     "expr": "scalar(\n    vmware_vm_mem_shared_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"}\n) / \n(\n    vmware_vm_mem_capacity{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} * 1024\n)\n* 100",
     "legendFormat": "Shared"
    },
    {
     "expr": "scalar(\n    vmware_vm_mem_vmmemctl_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} \n) / \n(\n    vmware_vm_mem_capacity{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} * 1024\n)\n* 100",
     "legendFormat": "Ballooned"
    },
    {
     "expr": "scalar(\n    vmware_vm_mem_swapped_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} \n) / \n(\n    vmware_vm_mem_capacity{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} * 1024\n)\n* 100",
     "legendFormat": "Swapped"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "label_replace(\n  (vmware_vm_net_bytesRx_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\", pfinstance!~\"vmnic.*|^vusb.*\"} * 8192),\n  \"nic\", \"vNIC$1\", \"pfinstance\", \".*([0-9]{1}$)\"\n)",
     "legendFormat": "rx: {{nic}} "
    },
    {
     "expr": "label_replace(\n  (vmware_vm_net_bytesTx_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\", pfinstance!~\"vmnic.*|^vusb.*\"} * -8192),\n  \"nic\", \"vNIC$1\", \"pfinstance\", \".*([0-9]{1}$)\"\n)",
     "legendFormat": "tx: {{nic}}"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vmware_vm_datastore_totalReadLatency_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} * \non (pfinstance) group_left(ds)\nvmware_datastore_info{vcenter=~\"$vcenter\"}",
     "legendFormat": "read: {{ds}} "
    },
    {
     "expr": "vmware_vm_datastore_totalWriteLatency_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} * \non (pfinstance) group_left(ds)\nvmware_datastore_info{vcenter=~\"$vcenter\"} * -1",
     "legendFormat": "write: {{ds}}"
    }
   ]
  },
  {
   "title": "Disk Troughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "vmware_vm_datastore_read_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} * \non (pfinstance) group_left(ds)\nvmware_datastore_info{vcenter=~\"$vcenter\"}",
     "legendFormat": "read: {{ds}} "
    },
    {
     "expr": "vmware_vm_datastore_write_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} * \non (pfinstance) group_left(ds)\nvmware_datastore_info{vcenter=~\"$vcenter\"} * -1",
     "legendFormat": "write: {{ds}}"
    }
   ]
  },
  {
   "title": "Disk Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "vmware_vm_datastore_numberReadAveraged_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} * \non (pfinstance) group_left(ds)\nvmware_datastore_info{vcenter=~\"$vcenter\"}",
     "legendFormat": "read: {{ds}} "
    },
    {
     "expr": "vmware_vm_datastore_numberWriteAveraged_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} * \non (pfinstance) group_left(ds)\nvmware_datastore_info{vcenter=~\"$vcenter\"} * -1",
     "legendFormat": "write: {{ds}}"
    }
   ]
  }
 ]
}